### ISSUE TITLE
`v2.7.3` breaks big endian targets

### ISSUE THREAD

**Issue by CryZe** [BurntSushi/memchr#152]
The latest version `2.7.3` apparently broke on all big endian targets. It does not identify the positions correctly anymore. I'll look deeper into what might've caused it.

**Comment by BurntSushi** [comment]
Hmmm I thought `powerpc64-unknown-linux-gnu` and `s390x-unknown-linux-gnu` were both big endian targets. Did I get that wrong? (Because of that, I perhaps have overvalued confidence in CI passing.)

**Comment by CryZe** [comment]
That's the targets that fail for me with 2.7.3:
https://github.com/LiveSplit/livesplit-core/actions/runs/9507202428/job/26206138350

I can try to modify my CI further to get actual example values that fail.

**Comment by CryZe** [comment]
Alright, this fails:
```rust
assert_eq!(memchr::memchr(b':', b"1:23").unwrap(), 1);
```
assertion `left == right` failed
  left: 2
 right: 1
```

**Comment by BurntSushi** [comment]
OK, so the test suite exploded with dozens of failures as soon as I ran it locally on the `powerpc64-unknown-linux-gnu` target. Then I checked the CI configuration and to my horror, `cargo` was being used in some of the steps instead of `cross` (when it's enabled): https://github.com/BurntSushi/memchr/blob/ad08893ecd23a21dc2fdb27cdaf04f64f4834270/.github/workflows/ci.yml#L125

I'm working on fixing it. If I can't fix it quickly, I'll revert the PR. I have an idea as to where the problem is.
