### ISSUE TITLE
Use std::arch::is_aarch64_feature_detected

### ISSUE THREAD

**Issue by axelkar** [BurntSushi/memchr#170]
It supports checking for Neon

**Comment by BurntSushi** [comment]
This issue is insufficient to act upon. Please elaborate. Are you hitting a problem with how things are done currently?

NEON is [part of `aarch64`](https://github.com/BurntSushi/memchr/blob/a7dbafe3736b9b1499203fb9f80a8a9f6e057ae9/src/arch/mod.rs#L11-L12) and [`memchr` gates `aarch64` on `target_arch = "aarch64"`](https://github.com/BurntSushi/memchr/blob/a7dbafe3736b9b1499203fb9f80a8a9f6e057ae9/src/arch/mod.rs#L11-L12). So it's not totally clear to me why we also need to be doing runtime CPU feature detection for `aarch64` when all we're using is NEON.

**Comment by BurntSushi** [comment]
I'm not 100% certain I'm correct, but I'm not 100% certain that link is correct either. And it might be that we are both correct. This is why I ask if you're experiencing a _specific_ problem. Because then we have something actionable to attack.

NEON might be optional in some cases, in the same way SSE2 is. For example, SSE2 might not be available on `x86`, but it's always available on `x86-64`. Although, even for `x86-64`, that isn't always true (which is why this crate uses runtime detection for `sse2` even on `x86-64`), since the OS needs to support the `xmm` registers. Maybe the same is true for NEON as well. I don't really know to be honest. And even then, it might be technically true, but basically never true in reality.

It's all very confusing and I find it difficult personally to find any oracle that can cut through all of this and give straight answers. The only real alternative is to focus on real issues as they come up as far as I can tell.
